server:
  port: 8081

mybatis-plus:
  mapper-locations: classpath:/com/demo/forest/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zhkz?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root

forest:
  resource-paths: ["/**"]
  exclude-paths: ["/css/**","/js/**","/img/**","/**/*.html","/libs/**","/user/login.ajax"]
  permission: true
